using System.Collections.Generic;
using UnityEngine;

namespace Game.AI.Shield {
	[DisallowMultipleComponent]
	public sealed class ShieldShockwaveAttack : MonoBehaviour {
		[Header("Damage")]
		[Tooltip("Attack data applied when the shockwave slam deals damage.")]
		[SerializeField] private AttackData shockwaveAttackData = new AttackData();

		[Header("Range")]
		[Tooltip("Maximum target distance allowed for starting the slam attack.")]
		[SerializeField] private float slamRange = 4.0f;

		[Header("Timing")]
		[Tooltip("Cooldown after a completed or attempted slam attack.")]
		[SerializeField] private float slamCooldown = 3.0f;
		[Tooltip("Minimum time the enemy remains attack-locked after starting the slam.")]
		[SerializeField] private float slamLockTime = 1.0f;
		[Tooltip("Duration of the exposed vulnerability window after the slam finishes.")]
		[SerializeField] private float slamExposeDuration = 1.25f;

		[Header("Shockwave")]
		[Tooltip("Radius of the shockwave area generated by the slam attack.")]
		[SerializeField] private float shockwaveRadius = 6.2f;
		[Tooltip("Layer mask used to detect damageable targets hit by the shockwave.")]
		[SerializeField] private LayerMask shockwaveDamageMask;
		[Tooltip("Layer mask used to detect ground surfaces for shockwave placement and effects.")]
		[SerializeField] private LayerMask shockwaveGroundMask = ~0;
		[Tooltip("How the shockwave overlap should treat trigger colliders.")]
		[SerializeField] private QueryTriggerInteraction shockwaveTriggerInteraction = QueryTriggerInteraction.Collide;

		[Header("Debug FX")]
		[Tooltip("Whether to spawn a debug shockwave ring visual when the slam is performed.")]
		[SerializeField] private bool spawnShockwaveDebugRing = true;
		[Tooltip("Optional prefab used to visualize the shockwave radius for debugging.")]
		[SerializeField] private GameObject shockwaveRingPrefab;
		[Tooltip("The lifetime (in seconds) that is the debug shockwave remains visible.")]
		[SerializeField] private float shockwaveDebugLifetime = 1.25f;

		[Header("Animation")]
		[Tooltip("Animator trigger name used to start the slam animation.")]
		[SerializeField] private string slamTriggerName = "Slam";

		// Reused shockwave buffers to avoid allocations when the slam attack runs
		private readonly Collider[] slamShockwaveOverlapBuffer = new Collider[32];
		private readonly HashSet<IDamageable> damagedTargets = new HashSet<IDamageable>();

		// Shield slam attack cooldown/state timers
		private float nextSlamTime = -Mathf.Infinity;
		private int slamTriggerHash;

		public float SlamRange => slamRange;

		private void Awake() {
			slamTriggerHash = Animator.StringToHash(slamTriggerName);
		}

		public void ResetRuntime() {
			nextSlamTime = -Mathf.Infinity;
		}

		public bool InSlamRange(float distanceToTarget) {
			return distanceToTarget <= slamRange;
		}

		public bool CanSlam(ShieldEnemy owner) {
			return owner != null
				&& owner.IsDead == false
				&& owner.IsStunned == false
				&& owner.IsAttacking == false
				&& owner.IsExposed == false
				&& Time.time >= nextSlamTime;
		}

		public bool TryStart(ShieldEnemy owner, Animator animator) {
			if (owner == null || owner.HasTarget == false) {
				return false;
			}

			if (CanSlam(owner) == false || InSlamRange(owner.DistanceToTarget) == false) {
				return false;
			}

			nextSlamTime = Time.time + slamCooldown;
			owner.BeginAttackLock(slamLockTime);

			if (animator != null) {
				animator.SetTrigger(slamTriggerHash);
			}

			return true;
		}

		public void DoShockwave(ShieldEnemy owner) {
			if (owner == null) {
				return;
			}

			AttackData attackData = BuildShockwaveAttackData(owner);
			Vector3 center = transform.position;

			// Cast a ray downwards to find the ground
			if (Physics.Raycast(transform.position, Vector3.down, out RaycastHit groundHit, 5.0f, shockwaveGroundMask, QueryTriggerInteraction.Ignore)) {
				center = groundHit.point;
			}

			// Spawn Shockwave Debug ring to visualise the AOE on the ground
			if (spawnShockwaveDebugRing && shockwaveRingPrefab != null) {
				GameObject ring = Instantiate(shockwaveRingPrefab, center + Vector3.up * 0.02f, Quaternion.identity);
				Destroy(ring, shockwaveDebugLifetime);
			}

			// Get colliders that overlap the Shockwave Slam AOE
			damagedTargets.Clear();

			int hitCount = Physics.OverlapSphereNonAlloc(center, shockwaveRadius, slamShockwaveOverlapBuffer, shockwaveDamageMask, shockwaveTriggerInteraction);

			for (int i = 0; i < hitCount; i++) {
				Collider hit = slamShockwaveOverlapBuffer[i];

				if (hit == null) {
					continue;
				}

				if (hit.transform.root == transform.root) {
					continue;
				}

				// Check if colliders in AOE contains a hurtbox (can it take damage)
				IDamageable damageable = hit.GetComponentInParent<IDamageable>();
				if (damageable == null || damagedTargets.Add(damageable) == false) {
					continue;
				}

				// A target can have multiple colliders, but should only take shockwave damage once
				damageable.TakeDamage(attackData);
			}

			owner.EnterExposedState(slamExposeDuration);
		}

		private AttackData BuildShockwaveAttackData(ShieldEnemy owner) {
			AttackData attackData = shockwaveAttackData;
			attackData.Attacker = owner != null ? owner.gameObject : gameObject;
			attackData.AttackerFaction = owner != null ? owner.OwnerFaction : Faction.Enemy;
			attackData.Type = DamageType.Melee;

			return attackData;
		}

		private void OnValidate() {
			slamRange = Mathf.Max(0.0f, slamRange);
			slamCooldown = Mathf.Max(0.0f, slamCooldown);
			slamLockTime = Mathf.Max(0.0f, slamLockTime);
			slamExposeDuration = Mathf.Max(0.0f, slamExposeDuration);
			shockwaveRadius = Mathf.Max(0.0f, shockwaveRadius);
			shockwaveDebugLifetime = Mathf.Max(0.0f, shockwaveDebugLifetime);
		}

		// - DEPRECATED - 

		// Does not apply Hurtbox damage logic
		//public void DoShockwave(ShieldEnemy owner) {
		//	if (owner == null) {
		//		return;
		//	}

		//	Vector3 center = transform.position;

		//	if (spawnShockwaveDebugRing && shockwaveRingPrefab != null) {
		//		GameObject ring = Instantiate(shockwaveRingPrefab, center + Vector3.up * 0.02f, Quaternion.identity);
		//		Destroy(ring, 1.25f);
		//	}

		//	Collider[] hits = Physics.OverlapSphere(center, shockwaveRadius, shockwaveDamageMask, QueryTriggerInteraction.Ignore);

		//	for (int i = 0; i < hits.Length; i++) {
		//		Collider hit = hits[i];
		//		if (hit == null || hit.transform == transform) {
		//			continue;
		//		}

		//		hit.SendMessage("ApplyAttackData", shockwaveAttackData, SendMessageOptions.DontRequireReceiver);
		//		hit.SendMessage("TakeDamage", shockwaveAttackData, SendMessageOptions.DontRequireReceiver);
		//	}

		//	owner.EnterExposedState(slamExposeDuration);
		//}
	}
}
